# Author: Greedysky <greedysky@163.com>

name: CI-Build

on: workflow_dispatch

jobs:
  qmmp-develop:
    uses: ./.github/workflows/develop.yml
    secrets: inherit

  qmmp-release:
    uses: ./.github/workflows/release.yml
    secrets: inherit
